### ISSUE TITLE
Error calling component for mapping registration

### ISSUE THREAD

**Issue by Salva5297** [helio-ecosystem/helio-rest#6]
When I try to add a new component to the rest service make a post request to this url:
```
 http://localhost:4567/api/cogito?builder=helio.jmapping.builder.JMappingBuilder
````
It gives me this error:
```
{
    "code": 500,
    "message": "helio.rest.exception.InternalServiceException: helio.blueprints.exceptions.ExtensionNotFoundException: Provided clazz is not a loaded component"
}
```

**Comment by AndreaCimminoArriaga** [comment]
The component must be registered using only the name. Your request should be:
`http://localhost:4567/api/cogito?builder=JMappingBuilder`
For making it work you should have imported that component before registering the mapping. Also consider that the JMappingBuilder is currently deprecated, it needs to be updated with the latest version of the Helio Blueprints
