### ISSUE TITLE
Creación de componente no devuelve #id

### ISSUE THREAD

**Issue by EmilioCrespoPeran** [helio-ecosystem/helio-rest#7]
Al realizar la petición POST hacia /component, se devuelve el mismo body que se envía.
Esto hace que no puedan eliminarse los componentes por id.

![image](https://user-images.githubusercontent.com/38924290/180555718-4e1758a5-56b2-4aa3-818c-7223a3f1e7c4.png)

**Comment by AndreaCimminoArriaga** [comment]
This feature has been included in the release [0.4.8](https://github.com/helio-ecosystem/helio-rest/releases/tag/v0.4.8)
